---
name: 01 - Build Blocks v.1

on: 
  push:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
      - name: Tworze pliki
        run: |
          echo "Plik nr 1" > C:\Users\tomas\moje_repo\plik1.txt
          echo "Plik nr 2" > C:\Users\tomas\moje_repo\plik2.txt
          echo "Plik nr 3" > C:\Users\tomas\moje_repo\plik3.txt
      - name: czekaj 60s
        run: sleep 60s
      - name: Wyświetlam zawartość
        run: cat C:\Users\tomas\moje_repo\plik1.txt C:\Users\tomas\moje_repo\plik2.txt