name: 02 – Workflow Events
on: 
  workflow_dispatch:
  schedule:
 #   - cron: '*/30 * * * *' # Uruchamiaj co 5 minut
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show the triggering event
        run: |
          echo "I' ve been triggered by the workflow_dispatch event ${{ github.event_name }}"
          ls -l
          date