name: 02 – Workflow Events
on: 
  schedule:
    - cron: '*/5 * * * *' # Uruchamiaj co 5 minut
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show the triggering event
        run: echo "I' ve been triggered by the workflow_dispatch event ${{ github.event_name }}"