---
name: 04 – Using actions
on: 
  workflow_dispatch:

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Echo something
        run: echo "Hello world from Ubuntu"