---
name: 04 – Using actions
on: 
  workflow_dispatch:

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    run: 
        working-directory: cwiczenia/react-app
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Echo something
        run: echo "Hello world from Ubuntu"
      - name: Install Dependencies
        run: npm ci
        
